# Python Crash Course
## Compbio Camp - February 2019
### Author: Chris Porras


**Welcome to Python!** <br>
This will be a brief crash course of the basic computational techniques that we will be using throughout this camp. 

### Some quick vocabulary:

> * __Jupyter Notebook__: a computational environment that allows us to neatly format and keep track of our Python code in <font color=blue>"notebooks"</font>. <br>
<br>
* __Cell__: the darker grey space below denoted by <font color=blue>"  In [ &ensp; ]  :  "</font>. Each cell is a convenient container for us to write a segment of Python code in. We can run the code inside of a cell using the `ctrl + enter` or `shift + enter` keyboard shortcuts. Cells are used to separate parts of our code that we want to run separately from one another.

## Let's jump into it!

### 1. Variable assignments and arithmetic

> Variables hold information in the form of integers, decimals (called ___"floats"___), words (called ___"strings"___ ), and others. We can assign values to variables with the " __=__ " assignment operator. Values assigned to variables are called ___"parameters"___ or ___"constants"___ and are stored in memory to be "called" by their variable names in other operations. 

In [16]:
## PS: We can write "comments" in cells using the '#'. 
# Writing comments is useful for annotating our code as we write it. 
# Comments are ignored when the code is run.

####### Example #######
a = 5
b = 0.5
c = "dogs" # strings can be written with either double "" or single '' quotes.

> We can also do standard arithmetic with variables and the __(+  ,  -  ,  *  ,  /  )__ operators. 

In [24]:
a + b

5.5

In [25]:
a - b

4.5

In [26]:
a * b

2.5

In [27]:
a / b 

10.0

> We can write exponents with the " __**__ " operator.

In [31]:
####### Example #######
2 ** 3

8

> __Notice__ that we get a `TypeError` when we try to perform arithmetic with an integer and a string. This is how Python lets us know that we're asking it to do something that doesn't make sense.

In [28]:
a + c

TypeError: unsupported operand type(s) for +: 'int' and 'str'

> When performing assignments, the variable names don't really matter as long as you are consistent with them. It's good coding practice to use descriptive but brief names.

In [29]:
####### Example #######
hrs_in_day = 24
num_days = 7

hrs_in_week = hrs_in_day * num_days

hrs_in_week

168

#### Practice:

> Write code using variable assignments to show the results of the following: <br>
1. $\frac{3}{2}\times 5$
2. $10\times 0.3$
3. $4^2 - 3$

In [43]:
####### YOUR CODE HERE #######
# 1.


In [44]:
####### YOUR CODE HERE #######
# 2.


In [45]:
####### YOUR CODE HERE #######
# 3.


> __Answers__:
1. 7.5
2. 3.0
3. 13

### 2. Lists

> * __Lists:__ are a useful data type that allows us to combine values into a single form. We can make lists with the " [&emsp;] " operator surrounding a sequence of values to combine. <br><br>
* __Function(&ensp;)__: the (&ensp;) denote functions. Functions can be fed inputs, or ___"arguments"___, and will perform operations and provide an output when run. 

In [55]:
####### Example #######
# We can assign lists to specific names to access the information sequence all at once
odd_nums = [1,3,5,7]

even_nums = [2,4,6,8]

# The print() function returns the values of its inputs. 

# Where before we needed to have separate cells for each single output,
# we can now use print() to show the outputs we want in the same cell. 

print(odd_nums)
print(even_nums)
print(odd_nums + even_nums) 

[1, 3, 5, 7]
[2, 4, 6, 8]
[1, 3, 5, 7, 2, 4, 6, 8]


> __Notice__ that adding lists _doesn't_ work the same way that adding variables does. Instead we combine the lists into larger ones. To perform typical arithmetic with lists we will need to convert them into a new data type that plays nicely with arithmetic operations.

### 3. Building arrays and vector arithmetic in `NumPy`

> * __Array__: A structure that stores a greater amount of information in an organized way (often arranged in rows and columns). The data stored in an array must be of the same type (integers, floats, etc.). <br> <br>
* __Vector__: An array that only has one row or one column of data. We also refer to these as ___"1-dimensional"___ arrays. <br><br>

> __NOTE__ : The following cell imports `NumPy`, a useful Python package for manipulating arrays. Please make sure to run that cell before continuing. 

In [2]:
import numpy as np

> Vectors can be thought of as a list of values, or a collection of variables. In the following examples, I will show how we can create vectors using `NumPy` and perform the same arithmetic operations as before.

In [5]:
####### Example #######
my_vec = np.array([2,3,5,7]) # Give the np.array() function a list to create an array from 

vec2 = np.array([2,4,6,8])

print(my_vec)
print(vec2)
print(my_vec + vec2) # Now we can do typical arithmetic with vectors

[2 3 5 7]
[2 4 6 8]
[ 4  7 11 15]


### 4. Indexing and loops

### 5. Conditional statements

### 6. Simple modeling and plotting data