# Python Crash Course
## Compbio Camp - February 2019
### Author: Chris Porras


# <font color=blue\>*YOUR NAME HERE*</font>

**Welcome to Python!** <br>
This will be a brief crash course of the basic computational techniques that we will be using throughout this camp. 

### Some quick vocabulary:

> * __Jupyter Notebook__: a computational environment that allows us to neatly format and keep track of our Python code in <font color=blue>"notebooks"</font>. <br>
<br>
* __Cell__: the darker grey space below denoted by <font color=blue>"  In [ &ensp; ]  :  "</font>. Each cell is a convenient container for us to write a segment of Python code in. We can run the code inside of a cell using the `ctrl + enter` or `shift + enter` keyboard shortcuts. Cells are used to separate parts of our code that we want to run separately from one another.

## Let's jump into it!

### 1. Variable assignments and arithmetic

> Variables hold information in the form of integers, decimals (called ___"floats"___), words (called ___"strings"___ ), and others. We can assign values to variables with the " __=__ " assignment operator. Values assigned to variables are called ___"parameters"___ or ___"constants"___ and are stored in memory to be "called" by their variable names in other operations. 

In [44]:
## P.S. We can write "comments" in cells using the '#'. 
# Writing comments is useful for annotating our code as we write it. 
# Comments are ignored when the code is run.

####### Example #######
a = 5
b = 0.5
c = "dogs" # strings can be written with either double "" or single '' quotes.

> We can do standard arithmetic with variables and the __(+  ,  -  ,  *  ,  /  )__ operators. 

In [24]:
a + b

5.5

In [25]:
a - b

4.5

In [45]:
a * b

2.5

In [27]:
a / b 

10.0

> We can write exponents with the " __**__ " operator.

In [43]:
####### Example #######
2 ** 3

8

> __Question__: What do you think will happen when we perform the following operation? <br>
`a + c`

In [46]:
####### YOUR CODE HERE #######


> __Answer__: we get a `TypeError` when we try to perform arithmetic with an integer and a string. This is how Python lets us know that we're asking it to do something that doesn't make sense. <br>
Was your prediction correct?

> When performing assignments, the variable names don't really matter as long as you are consistent with them. It's good coding practice to use descriptive but brief names.

In [47]:
####### Example #######
hrs_in_day = 24
num_days = 7

hrs_in_week = hrs_in_day * num_days

hrs_in_week

168

#### Practice:

> Write code using variable assignments to show the results of the following: <br>
1. $\frac{3}{2}\times 5$
2. $10\times 0.3$
3. $4^2 - 3$

In [43]:
####### YOUR CODE HERE #######
# 1.


In [44]:
####### YOUR CODE HERE #######
# 2.


In [45]:
####### YOUR CODE HERE #######
# 3.


> __Answers__:
1. 7.5
2. 3.0
3. 13

### 2. Lists

> * __Lists:__ are a useful data type that allows us to combine values into a single form. We can make lists with the " [&emsp;] " operator surrounding a sequence of values to combine. <br><br>
* __Function(&ensp;)__: the (&ensp;) denote functions. Functions can be fed inputs, or ___"arguments"___, and will perform operations and provide an output when run. 

In [21]:
####### Example #######
# We can assign lists to specific names to access the information sequence all at once
odd_nums = [1,3,5,7]

even_nums = [2,4,6,8]

# The print() function returns the values of its inputs. 

# Where before we needed to have separate cells for each single output,
# we can now use print() to show the outputs we want in the same cell. 

print(odd_nums)
print(even_nums)

[1, 3, 5, 7]
[2, 4, 6, 8]
[1, 3, 5, 7, 2, 4, 6, 8]


> __Question__: What do you think will happen when you perform the following operation? <br>
`print(odd_nums + even_nums)`

In [ ]:
####### YOUR CODE HERE #######


> __Answer__: adding lists _doesn't_ work the same way that adding variables does. Instead we combine the lists into larger ones. To perform typical arithmetic with lists we will need to convert them into a new data type that plays nicely with arithmetic operations. <br>
How did this compare to your prediction?

### 3. Building arrays and vector arithmetic in `NumPy`

> * __Array__: A structure that stores a greater amount of information in an organized way (often arranged in rows and columns). The data stored in an array must be of the same type (integers, floats, etc.). Arrays with only one row or one column of data are called ___"1-dimensional"___. <br> <br>

> __NOTE__ : The following cell imports `NumPy`, a useful Python package for manipulating arrays. Please make sure to run that cell before continuing. 

In [2]:
import numpy as np

> Arrays can be thought of as a list of values, or a collection of variables. In the following examples, I will show how we can create arrays using `NumPy` and perform the same arithmetic operations as before.

In [3]:
####### Example #######
my_arr = np.array([2,3,9,1]) # Give the np.array() function a list to create an array from 

arr2 = np.array([2,10,7,22])

print(my_arr)
print(arr2)
print(my_arr + arr2) # Now we can do typical arithmetic

[2 3 9 1]
[ 2 10  7 22]
[ 4 13 16 23]


**Practice:**

> Create the following arrays: <br>
       &#9656;  $\textbf{x}\ = (1,3,5,7,9)$ <br>
       &#9656;  $\textbf{y}\ = (2,4,6,8,10)$<br><br>
> Perform the following operations:
1. $\textbf{x}+\textbf{y}$
2. $\textbf{x}\times\textbf{y}$
3. $2\textbf{x}-\frac{\textbf{y}}{2}$ <br>

Please use `print()` to output your answers in the same cell.

In [48]:
####### YOUR CODE HERE #######


> __Answers__:<br>
1. array(  [ 3,  7, 11, 15, 19]  )
2. array(  [ 2, 12, 30, 56, 90]  )
3. array(  [ 1.,  4.,  7., 10., 13.]  )

### 4. Indexing and loops

> Let's say that instead of performing operations with the entire array, we only want to work with a specific subset of values in the array. *How can we do this?* <br><br>
Python arrays have an underlying identification system for each location in an array. Each location is given an "___index___" which counts from __0__ to the end of the array. We use "__[ 0 ]__" to get the first value in the array.<br><br>
Take a look at the following example:

In [12]:
####### Example #######
price = np.array([2.5,2.68,2.72,2.13,2.14]) 

print(price[0],"is the first value in price")
print(price[1:3],
      "are the second through the the fourth values in price (not including the fourth)")
print(price[-1],"gives the last value in price")

2.5 is the first value in price
[2.68 2.72] are the second through the the fourth values in price (not including the fourth)
2.14 gives the last value in price


> __Question__: How would you use indexing to change the __second__ element of the following array to a __7__?

In [16]:
####### YOUR CODE HERE #######
time = np.array([6.5,3,7.2,8,7.4])


> __Answer__:

In [15]:
time[1] = 7
print(time)

[6.5 7.  7.2 8.  7.4]


> Replacing specified values of an array with other values is hugely useful in scientific programming. 

> NEXT PROBLEMS:
1. REPEAT CALCULATION OF 2*X MANUALLY WITH INDEXING
2. UES FOR LOOPS TO DO IT

### 5. Conditional statements

> IF & ELSE FOR SIMPLE MODEL

### 6. Simple modeling and plotting data

> PREDATION MODEL